# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"

os: linux
dist: xenial
sudo: required

env:
  global:
    - TEST_CMD='py.test'
    - MPI_TEST_CMD='python'
  matrix:
    - MPI=mpich
    - MPI=openmpi

matrix:
  include:
    - python: 3.6
      env:
        - MPI=openmpi
        - TEST_CMD='py.test --cov --cov-append'
        # - MPI_TEST_CMD='coverage run -a' # if we can get coverage working...
        - MPI_TEST_CMD='python'
        - RUN_COVERAGE=true


before_install:
  - sh ci/travis/install-mpi.sh $MPI
  - pip install coveralls
  - pip install tox-travis

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install cython
  - pip install mpi4py>=3.0.0
  - pip install -r requirements.txt
  - pip install .

# command to run tests, e.g. python setup.py test
script:
  - mpiexec -n $P $MPI_TEST_CMD $PWD/tests/test_mpipso.py
  - $TEST_CMD

after_success:
  - if [ "$RUN_COVERAGE" = true ] ; then
        python -m coverage combine;
        coveralls;
    fi
